title = "Kohl's Admin"
gitRepoUrl = "https://github.com/kohls-admin/kohls-admin"
gitSourceBranch = "master"

changelog = true

[[classOrder]]
section = "Core"
classes = ["MainModule", "Auth", "Hook", "Process", "Registry", "Remote"]

[[classOrder]]
section = "Interface"
classes = ["UI", "Checkbox"]

[[classOrder]]
section = "Utility"
classes = ["Util", "Logger", "String"]

[docusaurus]
onBrokenLinks = "warn"
onBrokenMarkdownLinks = "warn"
trailingSlash = false
favicon = "/logo-dark.svg"
organizationName = "kohls-admin"
projectName = "main"
deploymentBranch = "gh-pages"
tagline = "Embrace creativity, not chaos."
url = "https://docs.kohl.gg"
baseUrl = "/"

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[[navbar.items]]
href = "https://kohl.gg/faq"
label = "FAQ"
position = "left"
target = "_self"
className = "no-link-icon"

[[navbar.items]]
href = "https://discord.gg/kohl"
label = "Discord"
position = "right"

[navbar.logo]
alt = "Kohl's Admin"
href = "https://kohl.gg"
src = "/logo-load.svg"
srcDark = "/logo-load-dark.svg"
target = "_self"

[footer]
style = "dark"
copyright = "Â© 2024 Kohl"
