title = "Kohl's Admin"
gitRepoUrl = "https://github.com/kohls-admin/main"
gitSourceBranch = "master"

changelog = true

[[classOrder]]
section = "Core"
classes = ["_K", "Auth", "Hook", "Flux", "Process", "Registry", "Remote"]

[[classOrder]]
section = "Interface"
classes = ["UI", "Checkbox"]

[[classOrder]]
section = "Utility"
classes = ["Util", "Logger", "Promise", "String"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/logo.svg"
organizationName = "kohls-admin"
projectName = "main"
deploymentBranch = "gh-pages"
tagline = "Embrace creativity, not chaos."
url = "https://docs.kohl.gg"
baseUrl = "/"

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[[navbar.items]]
href = "https://kohl.gg"
label = "Home"
position = "right"

[[navbar.items]]
href = "https://discord.gg/kohl"
label = "Discord"
position = "right"

[navbar.logo]
alt = "Kohl's Admin"
src = "/logo-load.svg"

[footer]
style = "dark"
copyright = "Â© 2024 Kohl"
