[package]
name = "kohltastrophe/kohls-admin"
description = "Embrace creativity, not chaos. Used by millions of developers, take control of your experience and try Kohl's Admin today."
authors = ["Kohl <admin@kohl.gg>"]
version = "0.2.3"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = [
	"src",
	"src/**",
	"default.project.json",
	"wally.toml",
	"LICENSE.md",
	"VERSION.txt",
]

[dependencies]
